name: Compliances

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
 compliance:
    runs-on: ubuntu-latest
 
   
    steps:
    - name: Advance Security Compliance Action
      uses: GeekMasher/advanced-security-compliance@v1.5
      with:
        token: ${{ secrets.JOHNPAT }}
        policy: johnjohncom/ghas-policy-as-code
        policy-path: policies/default.yml
           
